/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.BorderLayout;

import javax.swing.JFrame;

import control.Service;
import entity.Book;

/**
 *
 * @author looya
 */
public class Douban extends javax.swing.JFrame {

    /**
     * Creates new form Douban
     */
    public Douban() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTextField2 = new javax.swing.JTextField();
        searchHeading = new javax.swing.JLabel();
        searchKey = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        alt = new javax.swing.JLabel();
        translator = new javax.swing.JLabel();
        publisher = new javax.swing.JLabel();
        pubdate = new javax.swing.JLabel();
        binding = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        pages = new javax.swing.JLabel();
        summary = new javax.swing.JLabel();
        authorIntro = new javax.swing.JLabel();
        tags = new javax.swing.JLabel();
        ttitle = new javax.swing.JTextField();
        tsubtitle = new javax.swing.JTextField();
        tauthor = new javax.swing.JTextField();
        tpublisher = new javax.swing.JTextField();
        tprice = new javax.swing.JTextField();
        tbinding = new javax.swing.JTextField();
        talt = new javax.swing.JTextField();
        ttranslator = new javax.swing.JTextField();
        tpubdate = new javax.swing.JTextField();
        tpages = new javax.swing.JTextField();
        tisbn = new javax.swing.JTextField();
        ttags = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tauthorintro = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tsummary = new javax.swing.JTextArea();
        searchType = new javax.swing.JComboBox();
        bookinfo = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchHeading.setText("SERACH");

        searchKey.setColumns(20);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        title.setText("Title");

        isbn.setText("ISBN");

        author.setText("Author");

        subtitle.setText("Subtitle");

        alt.setText("Alt");

        translator.setText("Translator");

        publisher.setText("Publisher");

        pubdate.setText("Publish Date");

        binding.setText("Binding");

        price.setText("Price");

        pages.setText("Pages");

        summary.setText("Summary");

        authorIntro.setText("Author info");

        tags.setText("Tags");

        ttitle.setEditable(false);
        ttitle.setColumns(40);

        tsubtitle.setEditable(false);
        tsubtitle.setColumns(20);

        tauthor.setEditable(false);
        tauthor.setColumns(20);

        tpublisher.setEditable(false);
        tpublisher.setColumns(20);

        tprice.setEditable(false);
        tprice.setColumns(20);

        tbinding.setEditable(false);
        tbinding.setColumns(20);

        talt.setEditable(false);
        talt.setColumns(20);

        ttranslator.setEditable(false);
        ttranslator.setColumns(20);

        tpubdate.setEditable(false);
        tpubdate.setColumns(20);

        tpages.setEditable(false);
        tpages.setColumns(20);

        tisbn.setEditable(false);
        tisbn.setColumns(20);

        ttags.setEditable(false);

        tauthorintro.setEditable(false);
        tauthorintro.setColumns(20);
        tauthorintro.setLineWrap(true);
        tauthorintro.setRows(5);
        jScrollPane1.setViewportView(tauthorintro);

        tsummary.setEditable(false);
        tsummary.setColumns(40);
        tsummary.setLineWrap(true);
        tsummary.setRows(5);
        jScrollPane2.setViewportView(tsummary);

        searchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "name", "tag", "ID", "ISBN" }));

        bookinfo.setText("BOOK INFO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(search))
                            .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author)
                            .addComponent(subtitle)
                            .addComponent(title)
                            .addComponent(publisher)
                            .addComponent(binding)
                            .addComponent(price)
                            .addComponent(authorIntro)
                            .addComponent(tags)
                            .addComponent(bookinfo)
                            .addComponent(summary))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbinding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt)
                                    .addComponent(translator)
                                    .addComponent(pubdate)
                                    .addComponent(pages)
                                    .addComponent(isbn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(talt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tpages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tpubdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttranslator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ttitle)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(ttags)))
                    .addComponent(searchHeading))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchHeading)
                    .addComponent(bookinfo))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(ttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tsubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(talt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttranslator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(translator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tauthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpubdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(publisher, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tpublisher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pages, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tisbn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbinding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binding, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorIntro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tags))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(432, 432, 432))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        int id;
        id = Integer.parseInt(searchKey.getText());
        Service service = new Service();
        Book book = service.getBookByID(id);
        
        ttitle.setText(book.getTitle());
        tsubtitle.setText(book.getSubtitle());
        talt.setText(book.getAlt_title());
        tauthor.setText(book.getAuthorString());
        ttranslator.setText(book.getTranslatorString());
        tpublisher.setText(book.getPublisher());
        tpubdate.setText(book.getPubdate());
        tprice.setText(book.getPrice());
        tpages.setText(Integer.toString(book.getPages()));
        tbinding.setText(book.getBinding());
        tisbn.setText(book.getIsbn10()+" / "+book.getIsbn13());
        tsummary.setText(book.getSummary());
        tauthorintro.setText(book.getAuthor_intro());
        ttags.setText(book.getTagsString());
        
    }//GEN-LAST:event_searchActionPerformed

    protected void showbookinfo()
    {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Douban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Douban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Douban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Douban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Douban().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFrame f;
    private javax.swing.JLabel alt;
    private javax.swing.JLabel author;
    private javax.swing.JLabel authorIntro;
    private javax.swing.JLabel binding;
    private javax.swing.JLabel bookinfo;
    private javax.swing.JLabel isbn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel pages;
    private javax.swing.JLabel price;
    private javax.swing.JLabel pubdate;
    private javax.swing.JLabel publisher;
    private javax.swing.JButton search;
    private javax.swing.JLabel searchHeading;
    private javax.swing.JTextField searchKey;
    private javax.swing.JComboBox searchType;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel summary;
    private javax.swing.JLabel tags;
    private javax.swing.JTextField talt;
    private javax.swing.JTextField tauthor;
    private javax.swing.JTextArea tauthorintro;
    private javax.swing.JTextField tbinding;
    private javax.swing.JTextField tisbn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField tpages;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField tpubdate;
    private javax.swing.JTextField tpublisher;
    private javax.swing.JLabel translator;
    private javax.swing.JTextField tsubtitle;
    private javax.swing.JTextArea tsummary;
    private javax.swing.JTextField ttags;
    private javax.swing.JTextField ttitle;
    private javax.swing.JTextField ttranslator;
    // End of variables declaration//GEN-END:variables
}
